### ISSUE TITLE
This is really similar to Control.Monad.Free.Church

### ISSUE THREAD

**Issue by sgraf812** [isovector/too-fast-too-free#1]
As [/u/yakrar points out on reddit](https://www.reddit.com/r/haskell/comments/as1anb/freer_monads_too_fast_too_free_reasonably/egre27t), this seems to be really similar to [`Control.Monad.Free.Church` from `free`](http://hackage.haskell.org/package/free-5.1/docs/Control-Monad-Free-Church.html), judging from the instances. Just FYI.

Maybe you can inspire @ekmett to work out the connection to his blog post series? :) http://comonad.com/reader/2011/free-monads-for-less-2/

**Comment by sgraf812** [comment]
Gotcha

```
{-# LANGUAGE RankNTypes #-}

module Foo where

import Control.Monad

newtype Freer f a = Freer { runFreer :: forall m. Monad m => (forall t. f t -> m t) -> m a }

newtype F f a = F { runF :: forall r. (a -> r) -> (f r -> r) -> r }

f2Freer :: F f a -> Freer f a
f2Freer (F f) = Freer freer
  where
    freer exec = f return (join . exec)
```

So it seems `Freer` programs a slightly more general, because I can't come up with the other direction.

**Comment by sgraf812** [comment]
I really think you want to compare to the [`fused-effects`](http://hackage.haskell.org/package/fused-effects) approach from https://people.cs.kuleuven.be/~tom.schrijvers/Research/papers/mpc2015.pdf, who claim performance on par with `mtl`.

Basically, it also uses a specialisation of `Codensity`/`Cont` to have the same cheap bind instance (ignore the types, just look at the implementation, it's all `Cont`).

**Comment by isovector** [comment]
Hi! Thanks for the interest and the links! I'm traveling right now, but can't wait to take a look when I get a chance.

**Comment by isovector** [comment]
fwiw I think this is the inverse:

```haskell
freer2F :: Functor f => Freer f a -> F f a
freer2F (Freer m) = m $ \f -> F $ \kp kf -> kf $ fmap kp f
```

**Comment by isovector** [comment]
I went down this road for a bit; turns out the `F` monad doesn't optimize as nicely as just doing all of your binds in the eventual monad.

**Comment by masaeedu** [comment]
@isovector Is that also the case if you use the church encoded `FreerT` instead of `Freer`? The simplified version is:

```
data FreerInput f a r where
  Done :: a -> FreerInput f a r
  More :: forall x. f x -> (x -> r) -> FreerInput f a r

type FreerT f m a = forall r. (FreerInput f a (m r) -> m r) -> m r
```

The "eventual monad" is visible here as `m` in `FreerT`. The overall type of a computation in FreerT is just some function that accepts a monadic effect producing callback which can be fed effect requests, and somehow invokes it with a bunch of effect requests, sequencing them together into a final `m r` it spits out.

In `Control.Monad.Trans.Free.Church` they CPS away even that `FreerInput` datatype, but that version's really hard for me to wrap my head around.

**Comment by masaeedu** [comment]
The monad instance for `FreerT` of course doesn't require anything of anything; you don't even need a functor instance on `f`. So you should be able to use it with a functor that's an open union of functors or whatever else you like.
