### ISSUE TITLE
doesn't compile on my machine

### ISSUE THREAD

**Issue by gelisam** [isovector/too-fast-too-free#2]
You have a `stack.yaml` file, so I would have thought that reproducible builds would be guaranteed. Alas:

    $ stack build
    Building all executables for `too-fast-too-free' once. After a successful build of all of them, only specified executables will be rebuilt.
    too-fast-too-free-0.1.0.0: build (lib + exe)
    Preprocessing library for too-fast-too-free-0.1.0.0..
    Building library for too-fast-too-free-0.1.0.0..
    [5 of 7] Compiling Lib              ( src/Lib.hs, .stack-work/dist/x86_64-osx/Cabal-2.4.0.1/build/Lib.o )
    
    ./src/Lib.hs:53:12: error:
        • Occurs check: cannot construct the infinite type: a ~ (a, s)
          Expected type: s -> Eff (State s : r) a -> Eff r a
            Actual type: s -> Eff (State s : r) a -> Eff r (a, s)
        • In the expression:
            stateful
              $ \case
                  Get -> S.get
                  Put s' -> S.put s'
          In an equation for ‘runState’:
              runState
                = stateful
                    $ \case
                        Get -> S.get
                        Put s' -> S.put s'
        • Relevant bindings include
            runState :: s -> Eff (State s : r) a -> Eff r a
              (bound at src/Lib.hs:53:1)
       |
    53 | runState = stateful $ \case
       |            ^^^^^^^^^^^^^^^^...
    
    --  While building package too-fast-too-free-0.1.0.0 using:
          ~/.stack/setup-exe-cache/x86_64-osx/Cabal-simple_mPHDZzAJ_2.4.0.1_ghc-8.6.2 --builddir=.stack-work/dist/x86_64-osx/Cabal-2.4.0.1 build lib:too-fast-too-free exe:too-fast-too-free-exe --ghc-options " -ddump-hi -ddump-to-file"
        Process exited with code: ExitFailure 1

**Comment by isovector** [comment]
whoops. fixed!
